##Interactive documents / reports {#interactive}
* Use knitr with LaTeX or markdown to produce static documents
* Use shiny to make properly interactive reports

### Shiny overview
```
A web application framework for R
Turn your analyses into interactive web applications
No HTML, CSS, or JavaScript knowledge required
```
Uses magic and pixie dust to transform your R code into a webpage that provides end-users with the ability to analyse data interactively

##Shiny paradigm
It's call and response! 

* You have client-side controllers that tell server-side code to recalculate content  
* There are R functions for input controls, preparing content, and functions that output content.

##Shiny Server
You need a Linux server for this and your applications can be made internally or externally available.

Shiny is by default open, use either a [password system][2] or utilise AD integration in the [pro edition][3]

###Demo time!
```{r, echo=TRUE, eval=FALSE, results='asis'}
library(shiny)
system.file("examples", package="shiny")
runExample("03_reactivity") # a reactive expression
runExample("05_sliders") # sliders
```

[2]:http://withr.me/blog/2014/01/03/authentication-of-shiny-server-application-using-a-simple-method/
[3]:http://www.rstudio.com/products/shiny/shiny-server/