---
title: "Cut the R Learning Curve"
author: "Steph Locke (@SteffLocke)"
date:  "`r Sys.Date()`"
output:
  Rtraining::stephRevealSlideStyle
---

```{r autodoc, child='../../generics/AboutMe.Rmd', eval=TRUE}
```

# Agenda
## Agenda
- R
- R + Microsoft
- RefresheR
- Super R
- R for Reporting
- Develop R
- Administer R
- Wrap up

```{r autodoc, child='subDocs/Roverview.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/RMicrosoft.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/RefresheR.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/SuperR.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/Reporting.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/DevelopR.Rmd', eval=TRUE}
```

```{r autodoc, child='subDocs/AdministerR.Rmd', eval=TRUE}
```

# Wrap up
## Covered
- R overview
- R + Microsoft
- RefresheR
- Super R
- R for Reporting
- Develop R
- Administer R

## Next steps
- Get the deck & more at [bit.ly/stephsR](https://stephlocke.github.io/Rtraining)
- Follow up the Next Steps sections
- Let me know how you get on: @SteffLocke

## Q&A