---
output:
  md_document:
    variant: markdown_github
---
# Docker {data-background-iframe="https://www.docker.com/"}

## Docker
- Contained code
- Scripted infrastructure
- Bundled dependencies
- Lower maintenance than VMs

## Why use it?
- Scripted installs
- Saved from "Next, Next, Next"
- Insanely disposable
- Control your ops
- Rapidly developing

## Why not use it?
- Insanely disposable
- Control your ops
- Rapidly developing

## Why not use it? Versions {data-background="http://i.giphy.com/1SMYk3HBzaK3e.gif"}

## How to use it (locally)
- Install it
- Run the Docker Quickstart Terminal

```
docker run -it ubuntu /bin/bash
```

## How to use it - demo 
<iframe width="1280" height="720" src="https://www.youtube.com/embed/IK0JXZ_0dIs?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

## Docker-Machine
[docker-machine](https://docs.docker.com/machine/overview/) is needed to run containers, work on remote machines hosting docker containers, and to work with swarm clusters

## Docker plugins
[Plugins](https://docs.docker.com/engine/extend/legacy_plugins/) allow you to extend docker capabilities. Most plugins are network and file system related.

## Follow on
- [Why script infrastructure?](http://www.cio.com/article/3017722/infrastructure/what-is-infrastructure-as-code-and-why-should-you-embrace-it.html)
- [Get started with docker](https://docs.docker.com/windows/)