# Typical Inputs
## Dates
```{r}
shinyApp(
  ui = fluidPage(dateInput("datePicker", "Pick a date:", format="dd/mm/yy"),
                 dateRangeInput("dateRange", "Pick dates:", 
                                start=Sys.Date(), end=Sys.Date()) ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```

## Values | Simple
```{r}
shinyApp(
  ui = fluidPage(numericInput("vals", "Insert a number:", value=15, min=10)  ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```

## Values | Sliders
```{r}
shinyApp(
  ui = fluidPage(sliderInput("vals", "Insert a number:", 
                             min=0, max=50, value=15)  ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```

## Text | Single line
```{r}
shinyApp(
  ui = fluidPage(textInput("char", "Insert text:")  ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```

## Text | Paragraph
```{r}
shinyApp(
  ui = fluidPage(tags$textarea(id="charbox", rows=3, cols=40, "Default value")  ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```


## Selectors 
```{r}
shinyApp(
  ui = fluidPage(selectInput("multiselect", "Pick favourites:",
                             c("Green","Red","Blue"),
                             multiple=TRUE)  ),
  server = function(input, output) {}
  ,options=defaultdisplay
)
```

## List of input types

```{r, echo=FALSE}

data.table(`Input controls`=lsp(shiny,pattern = "Input"))
```